### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by mikespax** [niklasravnsborg/front-export#2]
Is this still working? These are the errors I've received recently.

TypeError: Cannot read property 'status' of undefined
    at axios.interceptors.response.use.err
(/Users/Sparks/Downloads/front-export-master/lib/api.js:23:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

and then this one

(node:4131) UnhandledPromiseRejectionWarning: Error: Request failed with status code 502

    at createError (/Users/Sparks/Downloads/front-export-master/node_modules/axios/lib/core/createError.js:16:15)

    at settle (/Users/Sparks/Downloads/front-export-master/node_modules/axios/lib/core/settle.js:18:12)

    at IncomingMessage.handleStreamEnd (/Users/Sparks/Downloads/front-export-master/node_modules/axios/lib/adapters/http.js:191:11)

    at IncomingMessage.emit (events.js:187:15)

    at endReadableNT (_stream_readable.js:1094:12)

    at process._tickCallback (internal/process/next_tick.js:63:19)

(node:4131) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1418)

(node:4131) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by niklasravnsborg** [comment]
Hey Mike! Should be working since the API didn't change. I don't have a front account anymore. If you send me your credentials I might be able to help you.

Niklas

**Comment by mikespax** [comment]
I sent an email. Did you get it? You can close this issue anyways.

**Comment by mikespax** [comment]
Any idea when you'd be able to check this out?
